### ISSUE TITLE
Update method rules() in next versions.

### ISSUE THREAD

**Issue by Auramel** [yiisoft/validator#1]
Hello!
So, I offer to change syntax in \yii\base\Model::rules()

For example, now we have

```php
public function rules()
{
	return [
		[['login', 'pass'], 'required']
	];
}
```

I offer try to code something else, for example:
```php
public function rules()
{
    return [
        $this->login => Validator()->required()->string()->min(255)->max(1000)
    ];
}
```

I like [https://github.com/Respect/Validation](https://github.com/Respect/Validation) approach. What do you think?
**UPD:** I don't know why tabs and spaces are not working...
**UPD2:** Someone fixed it. Thank you 👍 

Russian: хотелось бы писать правила, как в ссылке выше. :) 
**UPD:** Хз почему все переносы и табы слетели... Писал в Notepad++...

**UPD2:** Кто-то пофиксил. Спасибо 👍

**Comment by samdark** [comment]
This one is now implemented.
