### ISSUE TITLE
getActiveValidators initializes unnecessary validators

### ISSUE THREAD

**Issue by bizley** [yiisoft/validator#10]
[Model::getActiveValidators()](https://github.com/yiisoft/yii2/blob/2.0.11.2/framework/base/Model.php#L422) calls [Validator::isActive()](https://github.com/yiisoft/yii2/blob/2.0.11.2/framework/validators/Validator.php#L391) which does not take into account attributes present in the scenario - it only checks if scenario is not listed in the `except` property and `on` property is empty or scenario is listed there. With common use case where attributes are listed for the scenario in `scenarios()` method these conditions return still `true` for validators related to attributes not listed in scenario.

This looks like a bug and unnecessary memory consumption but maybe there is a reason behind this?

| Q                | A
| ---------------- | ---
| Yii version      | 2.0.11.2

**Comment by samdark** [comment]
Not applicable to new desing.
