### ISSUE TITLE
Use Injector in the Callback rule

### ISSUE THREAD

**Issue by viktorprogger** [yiisoft/validator#113]
This will give the ability to use callables with dependencies as validation rules.
One more question here: should the injector be optional to support projects without DI container?

**Comment by samdark** [comment]
The bad thing is that it will make the package dependent on yiisoft/injector.

**Comment by viktorprogger** [comment]
This dependency may be optional

**Comment by vjik** [comment]
Callback rule almost always used into something class, where we can get dependencies from constructor and use their in rule via `$this->`. I think add injector in this rule is overhead.

**Comment by samdark** [comment]
See https://github.com/yiisoft/validator/pull/127#issuecomment-846532958
