### ISSUE TITLE
validate(&$value, &$error = null) and validateValue(&$value)

### ISSUE THREAD

**Issue by bscheshirwork** [yiisoft/validator#13]
### What steps will reproduce the problem?
I try to create "validator" class.
Validation can change a values under validation (like filter validator)
I wish use `validate` and nested `validateValue` functional
I can't change the value in this way.
I am right?

So... How about change signature? Or other way needed?

### Additional info

| Q                | A
| ---------------- | ---
| Yii version      | 2.0.13@dev
| PHP version      | 7.1.11
| Operating system |

**Comment by samdark** [comment]
Not an issue with current implementation.
