### ISSUE TITLE
Adjust "skipOnEmpty"

### ISSUE THREAD

**Issue by vjik** [yiisoft/validator#132]
1. Empty values always should be validate when rule using separately. For example, `(new Number())->validate('')->isValid()` should return `false`.

2. Validate or not validate value should be decided not at rule level, but above (maybe validator or form).

3. Check on empty can be differenet in cases. For example, `null` is empty, but empty string `''` is not empty.

**Comment by samdark** [comment]
1. Yes and no. This behavior is expected to be default but I'm not sure "always" applies here.
2. Higher level could pass it to lower level.
3. Correct. What do you propose? Is it broken?

I'd keep the skipOnEmpty option at Rule level but ensure that default for individual rule is "false".

**Comment by vjik** [comment]
> 1. Yes and no. This behavior is expected to be default but I'm not sure "always" applies here.

Maybe... But I think better construction `if (!empty($value) && $rule->validate($value)) ...` than `if ($rule->validate($value)->skipOnEmpty(true)) ...`. We clearly understand which values are empty.

> 2. Higher level could pass it to lower level.

If higher level could pass it to lower level, then we have unclear behavior in case when for some rule will be set `skipOnEmpty` manually.

> 3. Correct. What do you propose? Is it broken?

Remove `skipOnEmpty` from rule :)

**Comment by samdark** [comment]
I'm fine with removing `skipOnEmpty` from rule but behavior itself should be kept. For example, it's needed for HTML form with:

1. First name (required, a-z)
2. Last name (required, a-z)
3. Patronymic (optional, a-z)

Patronymic here is optional. Means if it's empty string in the form submit, everything's OK but if it's "123" then we need to error.

See https://github.com/yiisoft/validator/pull/108

**Comment by rustamwin** [comment]
Does current Rule/Handler mechanism solves this issue?

**Comment by samdark** [comment]
In general, we have two modes:

1. HTML forms. There empty values are always passed.
2. API. There empty values are not passed.

To switch between the two:

1. Add ability to specify callback for `skipOnEmpty`. Return value will determine what empty is.
2. Values could be `true`, `false`, callback.
3. Could be specified at Validator and Rule level.
4. Create default callback classes for `SkipOnAbsent` (or `SkipOnNull`), `SkipOnEmpty`. Specify `SkipOnEmpty` as default at validator level.

**Comment by arogachev** [comment]
> Specify SkipOnEmpty as default at validator level.

For validator I think it's better to specify it explicitly, because it can be also set differently for multiple rules.
