### ISSUE TITLE
Validate nested data

### ISSUE THREAD

**Issue by andrew-svirin** [yiisoft/validator#135]
Hi,
Is any example how to validate complex data?
Like:
```php
[
 'name' => 'Name',
 'address' => [
   'city' => 'City', 
 ],
]
```

**Comment by samdark** [comment]
https://github.com/yiisoft/validator/pull/98

**Comment by andrew-svirin** [comment]
Perfect!

**Comment by andrew-svirin** [comment]
And this option is also possible?
```php
[
 'users' => [
   [
     'name' => 'Name1',
   ],
   [
     'name' => 'Name2',
   ]
 ]
]
```

**Comment by samdark** [comment]
I don't remember. Try it.

@xepozz maybe you remember if it was implemented or just planned to be implemented?

**Comment by xepozz** [comment]
I don't sure that it's possible as `NestedRule`, but you can try to combine it with `Each` or another rules.

**Comment by samdark** [comment]
@andrew-svirin please post about your results. Will help us.

**Comment by andrew-svirin** [comment]
@samdark Okay. I will do soon.

**Comment by andrew-svirin** [comment]
First of all - Thank you!

Q1:
Every time worked with complex DTO I faced problem in validation:
For example incoming request:
```json
{
 "username": "Nick",
 "email": "test@email",
 "purchase" : [
    {
      "product_id": "111-111-abc",
      "amount" : 111
    }
    ...
 ]
...
}
``` 
In example is demonstrated that request can hold multiple entities those should be saved in transaction.
Question is:
1. Should I combine multiple Validators to validate DTO? Does Yii support reuse validators?
2. Should I duplicate validation rules?
Could you suggest the correct approach when using Yii3.

Q2:
Will be road map how to migrate business logic from Yii2 to Yii3? How to write validation for js framework? What js framework will recommend Yii3?

And also I collected some other tools that could be common problems when working with framework:
1. phpstorm-plugin for Yii3. This is a big plus to any framework.
2. Flexible event-listener configuration to realise relations between modules. And is possible to have cached configuration-per-controller?
3. Flexible declaration relations between entities that can be used for building composite data response?
4. Would Yii3 can make some services private for module?

**Comment by xepozz** [comment]
> Should I combine multiple Validators to validate DTO?
Should I duplicate validation rules?

As you wish.

> Does Yii support reuse validators?

[Yes, it is](https://github.com/yiisoft/validator/#creating-your-own-validation-rules).


> How to write validation for js framework?

Rules provide options in [simple format](https://github.com/yiisoft/validator/issues/43#issuecomment-569916868) so you can make wrapper for any JS framework.
Unfortunately, JS adapters aren't written.

> What js framework will recommend Yii3?

Any :)

----

More helpful information you can find in [docs](https://github.com/yiisoft/docs).

**Comment by jin2chen** [comment]
@andrew-svirin Reference https://github.com/jin2chen/yii-validator

**Comment by arogachev** [comment]
@andrew-svirin It's already possible with current API. The missing part that is crucial is error details (see #147). Please refer to example in #151 (error details are also added).

@jin2chen Nice attempt, but we can use existing `Nested` and `Each` for achieving the same thing.
