### ISSUE TITLE
Validate models with DI

### ISSUE THREAD

**Issue by andrew-svirin** [yiisoft/validator#136]
Hi!
1. I want to validate directory, so want to inject filesystem dependency. Is any example witch way inject dependency into custom rule?
2. Where gone validation rule ActiveRecord Exists after Yii2? :) is any solution to validate record already exists in database?

**Comment by samdark** [comment]
1. Pass dependencies via rule constructor.
2. Not implemented yet and likely will be a separate package.

**Comment by andrew-svirin** [comment]
@samdark but constructor marked as `final` or it is not matter?

**Comment by samdark** [comment]
I've meant static constructor. There's an example:

```php
public static function rule(int $count): self
{
    $rule = new self();
    $rule->count = $count;
    return $rule;
}
```

**Comment by andrew-svirin** [comment]
@samdark 
So the correct way
```php

class ProjectValidator {

public function __constructor(FilesystemInterfase $fs)
{
 $this->fs = $fs;
}

public function validate()
{
...
}

private function getcreateRules()
{
return [
 'dir' => DirExists::create($this->fs),
];

}

```

```php
class DirExists extends Rule
{

public $fs;

public static function create($fs)
{
 $rule = new self();
 $rule->fs = $fs;

 return rule;
}
}
```

May be shorter way to have inject `FilesystemInterface $fs` into `DirExists::__constructor()` ?

**Comment by andrew-svirin** [comment]
I do not like this approach, because I need to have rule rather then filesystem.

So then will be better to add factory for rule that supports DI. (rule constructor is locked)


```php
class ProjectValidator {

 public function __constructor(DirExistsFactory $dirExistsFactory)
 {
  $this->dirExistsFactory = $dirExistsFactory;
 }

 public function validate()
 {
  ...
 }

 private function getcreateRules()
 {
  return [
   'dir' => $this->dirExistsFactory->create(),
  ];
 }
}
```

```php
class DirExistsFactory {
 public function __constructor(FilesystemInterfase $fs)
 {
  $this->fs = $fs;
 }

 public function create()
 {
   $rule = new self();
   $rule->fs = $this->fs;

   return $rule
 }
}
```

```php
class DirExists extends Rule
{

 public $fs;

 protected function validateValue($value, ValidationContext $context = null): Result
 {
  ...
 }
}
```

The the question: Is this example helpful? 
https://github.com/yiisoft/validator/blob/a20a6f4f6ab9f3175233e22156daefdbed6059cf/src/Rule.php#L39
