### ISSUE TITLE
[2.1|3.0] proposal ActiveRecords class without validation first

### ISSUE THREAD

**Issue by Insolita** [yiisoft/validator#14]
In some simple cases internal model validation not bad, but in more complex cases when validation is in separate classes and save/update operations wrapped into services/repositories, validation-scenario functional seems like overhead and thereare reasons for prohibit direct usage of ```$model->load($data) && $model->validate() ```  and internal rules configuration; 

So my proposal -  extract validation feature in trait and add something like SelfValidationInterface, instead of  ```BaseActiveRecord extends Model```

**Comment by samdark** [comment]
Out of scope of this package.
