### ISSUE TITLE
Make Rules composite

### ISSUE THREAD

**Issue by kriptogenic** [yiisoft/validator#141]
Extend from Rule abstract class or implement RuleInterface, than behavior of Rules class will be same as any rule.

P.S. 
This idea was in refactoring stream

**Comment by arogachev** [comment]
@kriptogenic Could you provide more details? Link to that refactoring stream could be useful too.

**Comment by arogachev** [comment]
@vjik Maybe you have timestamp as well? :slightly_smiling_face:

**Comment by vjik** [comment]
> @vjik Thanks! Maybe you have timestamp as well? 🙂

No, I haven't watched it :)

**Comment by arogachev** [comment]
Got it. Then I'll move it to a further milestone due to a lack of details and response from author.

**Comment by arogachev** [comment]
Closing due to a lack of details. Feel free to reopen with new info.

**Comment by arogachev** [comment]
https://youtu.be/liMyAuxIoyM?t=4255

**Comment by samdark** [comment]
This one is no longer valid.
