### ISSUE TITLE
Url rule by default generate wrong input pattern attribute

### ISSUE THREAD

**Issue by Gerych1984** [yiisoft/validator#144]
Good day. When I add `Url::rule` to some FormModel and using it with Field widget - that generate input with pattern attribute. But by default that pattern give browser error with url contains only scheme and domain (and works with url also contains path). Anyway - by default it will be browser error for cyrillic URLs. So - maybe remove pattern option from `getOptions`? Thanks

**Comment by samdark** [comment]
There are no cyrillic URLs. Only IDN and how browsers are masking them: https://en.wikipedia.org/wiki/Punycode

**Comment by Gerych1984** [comment]
> There are no cyrillic URLs. Only IDN and how browsers are masking them: https://en.wikipedia.org/wiki/Punycode

Ok - I agree that cyrrilic url it's worst thing. But it's input (not backend validation, where I set `Url::enableCDN` equals true). And what I must say people's, who using form with that input - you should convert https://дом.рф/** and etc to punycode to send it ) ? Maybe compromise - change `getOptions` like that?

```
pattern  => $this->enableIDN ? null : $this->pattern
```

**Comment by Gerych1984** [comment]
Litle remark for issue - that pattern does not allow [any urls](https://jsfiddle.net/zLkmn2vf/)

**Comment by samdark** [comment]
Fixed.
