### ISSUE TITLE
Allow to use flat array as input for Nested and Each rules

### ISSUE THREAD

**Issue by arogachev** [yiisoft/validator#154]
Extracted from #151. Or maybe this should be implemented at another level (forms, etc. - need to discuss).

**Comment by vjik** [comment]
Can you show example?

**Comment by samdark** [comment]
Dot-separated?

```php
'submodel.field' => Required::class
```

**Comment by vjik** [comment]
Replace `Each::rule(new Rules($rules))` to `Each::rule($rules)` ?

This is major change. I think we should make this before first release.
