### ISSUE TITLE
`Rules::asArray()` should return all rules

### ISSUE THREAD

**Issue by vjik** [yiisoft/validator#156]
https://github.com/yiisoft/validator/blob/d8d7b602d44f21f6fac1fda4164771238881bc10/src/Rules.php#L91-L100

We should for unparametrized rules return also item with rule name and empty options. because unparametrized rules also can be implemented in frontend.

**Comment by samdark** [comment]
How would you convert it? The whole purpose of `ParametrizedRuleInterface` is to declare "I can be represented as an array".

**Comment by vjik** [comment]
> How would you convert it? The whole purpose of `ParametrizedRuleInterface` is to declare "I can be represented as an array".

As empty array, that is, a rule that does not require parameters.

**Comment by samdark** [comment]
Makes sense.
