### ISSUE TITLE
Add method to get nested tree of errors

### ISSUE THREAD

**Issue by arogachev** [yiisoft/validator#167]
In #151 we decided to implement it later in external class accepting list of error objects.

**Comment by samdark** [comment]
Done.

**Comment by samdark** [comment]
Need an example of use-case.

**Comment by arogachev** [comment]
@samdark https://github.com/yiisoft/validator/pull/151/commits/8732f47ed1de4347166b400bb1d898aaa8e546ce. If I remember correctly, the problem was how to display errors for `coordinates` for example? Using numeric keys along with `x` and `y`? This could be confusing. Use a subarray with reserved key name? We discussed that external class could solve this issue, but unfortunately I don't remember details. I don't have an exact use case also. Maybe delay it until it's requested?

**Comment by arogachev** [comment]
Let's close it until we have a practical case for this or it will be requested by other users.
