### ISSUE TITLE
Consider using Respect library

### ISSUE THREAD

**Issue by samdark** [yiisoft/validator#17]
https://github.com/Respect/Validation potentially could replace this package.

**Comment by FabrizioCaldarelli** [comment]
This could be a new thinking way for Yii 3 to avoid to reinvent the wheel in similar cases.

We can use external libraries instead rewriting on our own ( for example could be the same with guzzlehttp, etc. etc.), but we keep in mind that Yii stability will be dependent from these external libraries. If their developer make some BC in the code, Yii will have problems.

I suggest a middle way. What do you think about creating a fork for each external library used, for example Respect/Validation, called yii-respect-validation, so we have 3 benefits:

1) full control of source code and eventually BC;
2) we can insert our customization;
3) we can check external library updates before merge them in official yii library version;

**Comment by machour** [comment]
@FabrizioCaldarelli you can simply lock versions in composer.json instead. 
Maitaining a fork with our own customization really doesn't sound like a good plan.

**Comment by FabrizioCaldarelli** [comment]
Sure we can lock, but how can we customize It if we need?

**Comment by KartaviK** [comment]
i think creating a fork for every external library that can potentially  used in project not good idea. For every patch/minor verdion you must merge changes. And also if forked package was customised - it can be more problems

**Comment by samdark** [comment]
Decided to go with our own thing. Respect is too different design-wise.
