### ISSUE TITLE
Refactoring `ParametrizedRuleInterface`

### ISSUE THREAD

**Issue by vjik** [yiisoft/validator#172]
Interface `ParametrizedRuleInterface` is needed for convert rules to array for their subsequent pass to the client and then used for client-side validation. The current name is confusing, `parametrized` may mean that the rules can be set parameters.

Also on convert rules to array we converted all rules: if rule is not `parametrized`, then used rule class name as rule name:

https://github.com/yiisoft/validator/blob/045fd33228aa15a0f62eab5912fc3a22a027fc01/src/RuleSet.php#L96-L107

I think, this is not right and non-consistent.

We should use one of two way:

1) Remove `getName()` from `ParametrizedRuleInterface` and always use class name as rule name.

2) Rename `ParametrizedRuleInterface` to `SerializedRuleInterface` and convert to array only rules that implemented this interface.

**Comment by samdark** [comment]
1. OK.
2. https://github.com/yiisoft/validator/issues/156

**Comment by vjik** [comment]
I'm missed that abstract `Rule` use class name without namespace for name of rule.
For consistency we should use class name without namespace for non-parametrized rules.

Also suggest so refactoring:

1) Move code for generate rule name to separate helper:
https://github.com/yiisoft/validator/blob/045fd33228aa15a0f62eab5912fc3a22a027fc01/src/Rule.php#L185-L186

2) Create new interface `NamedRuleInterface` which will contain method `getName(): string` 

3) Abstract `Rule` implement  `NamedRuleInterface`.

4) In `RuleSet::asArray()` for rules that implemented `NamedRuleInterface` use `getName()` method and for rest of rules generate rule name from class name.

**Comment by samdark** [comment]
Renamed the interface in #257. The rest isn't valid anymore or is desired beahvior.
