### ISSUE TITLE
Make behavior of Required rule more clear

### ISSUE THREAD

**Issue by arogachev** [yiisoft/validator#173]
- https://t.me/yii3en/5108
- https://t.me/yii3en/5109
- https://t.me/yii3en/5119 (first part).

**Comment by samdark** [comment]
Related to https://github.com/yiisoft/validator/issues/213

**Comment by samdark** [comment]
In docs need to explicitly mention that fields are not required by default and `required` should be specified explicitly.

**Comment by arogachev** [comment]
@samdark Seems like this was mislooked. The issue is not about explicitly specifying `Required` ruile, but about its behavior - it throws exception on missing data. I'll recheck this.

**Comment by arogachev** [comment]
Update: checked it. This is still actual. I think the behavior needs to be indeed changed to just adding error message.
