### ISSUE TITLE
Rename MatchRegularExpression

### ISSUE THREAD

**Issue by arogachev** [yiisoft/validator#180]
Maybe `Regex` or `Regexp`? Both are widely used abbreviations. Or at least just `RegularExpression`? The current name is a bit verbose and not consistent compared to others.

**Comment by vjik** [comment]
I agree, `MatchRegularExpression` non-consistent with other rules.
All suggested names is OK to me.
Vote?

🎉 — `Regex`
🚀 — `Regexp`
❤️ — `RegularExpression`

**Comment by arogachev** [comment]
Already fixed as `Regex` in #175. But I can rename it to something else if needed.

**Comment by samdark** [comment]
Regex sounds alright.
