### ISSUE TITLE
Add `Count` rule

### ISSUE THREAD

**Issue by arogachev** [yiisoft/validator#185]
Add support for array to `HasLength`.

For example:

https://github.com/yiisoft/validator/blob/e94fe51063a7f2073cac28a9acfaf5220d4e3646/tests/Rule/NestedTest.php#L226-L228

We also need to check that array contains exactly 3 elements. And it's quite common case. Currently this can be solved with custom rule or `Callback` rule, but it's a bit verbose.

Or it can be added to another rule if it goes against `HasLength` philosophy.

https://github.com/yiisoft/validator/blob/e94fe51063a7f2073cac28a9acfaf5220d4e3646/src/Rule/HasLength.php#L62-L65

**Comment by xepozz** [comment]
> Or it can be added to another rule if it goes against `HasLength` philosophy.

I think it's right way. Just implement new `Count` rule. WDYT?

**Comment by samdark** [comment]
`Count` sounds alright.
