### ISSUE TITLE
Add a more convenient way to configure the same properties for multiple rules

### ISSUE THREAD

**Issue by arogachev** [yiisoft/validator#186]
For example, formatter. For usages like this it can quickly become a hassle.

https://github.com/yiisoft/validator/blob/e94fe51063a7f2073cac28a9acfaf5220d4e3646/tests/Rule/NestedTest.php#L209-L233

**Comment by arogachev** [comment]
For rule set it's possible to use common formatter though, but other properties, such as `skipOnError`, etc., still need to be duplicated.

https://github.com/yiisoft/validator/blob/e94fe51063a7f2073cac28a9acfaf5220d4e3646/src/RuleSet.php#L40

**Comment by arogachev** [comment]
The same applies to `RulesDumper`:

https://github.com/yiisoft/validator/blob/e94fe51063a7f2073cac28a9acfaf5220d4e3646/src/RulesDumper.php#L72

I think the better way is to set formatter during configuration / initialization process for each rule individually.

**Comment by arogachev** [comment]
`Validator` can't fully handle this too for more complex structures (`Nested` + `Each` combinations).

https://github.com/yiisoft/validator/blob/e94fe51063a7f2073cac28a9acfaf5220d4e3646/src/Validator.php#L42

**Comment by samdark** [comment]
Can't you get an instance of a rule and then re-use it multiple times?

**Comment by arogachev** [comment]
Was it fixed by #234? @vjik

**Comment by arogachev** [comment]
Working on it.
