### ISSUE TITLE
Fix negated checks for instanceof

### ISSUE THREAD

**Issue by arogachev** [yiisoft/validator#188]
https://github.com/yiisoft/validator/blob/e94fe51063a7f2073cac28a9acfaf5220d4e3646/src/RuleSet.php#L72

needs to be rewritten as 

```php
if (!($rule instanceof RuleInterface)) {
```

And it's not the only one occurrence.

**Comment by arogachev** [comment]
My bad, the result will be the same in both cases, so it's only a readability issue. Maybe I'll move it to https://github.com/yiisoft/docs later (to mention it somewhere in https://github.com/yiisoft/docs/blob/master/010-code-style.md).

**Comment by andrew-demb** [comment]
https://www.php.net/manual/en/language.operators.precedence.php

**Comment by arogachev** [comment]
@andrew-demb Thanks, no need to mention in it in code style then obviously. Don't know why I was certain that negation has higher priority.
