### ISSUE TITLE
Are GroupRule and RuleSet really needed now?

### ISSUE THREAD

**Issue by arogachev** [yiisoft/validator#189]
Can use `Nested` rule instead and rename it, for example `RuleComposite`.

**Comment by samdark** [comment]
`GroupRule` purpose is to conveniently reuse multiple rules by defining your own class i.e.

```php
final class RequiredNotBlacklistedEmail
{
    protected function getRuleSet(): RuleSet
    {
        return new RuleSet([
            new Required(),
            new Email(),
            $this->getNotBlacklistedRule(),
        ]);
    }

    private function getNotBlacklistedRule(): Rule
    {
        return new class extends Rule() {
           protected function validateValue($value, ValidationContext $context = null): Result
           {
               // check if email is blacklisted
           }
        }
    }
}
```

`RuleSet` can't let you do the same compile-time and in `Nested` you have to define what to validate exactly but `RequiredNotBlacklistedEmail` could be applied to many different structured through the application.
