### ISSUE TITLE
Unable to set formatter when using attributes

### ISSUE THREAD

**Issue by arogachev** [yiisoft/validator#197]
Related - #175.

- Passing instances is only allowed since PHP 8.1.
- Can't extend from specific rule (`Number` for example) to override just this property. Can be solved with extending from base `Rule` / composition, but isn't it over-complication?

**Comment by arogachev** [comment]
Also related - #186.

**Comment by vjik** [comment]
> * Passing instances is only allowed since PHP 8.1.
In this case suggest leave it as it is. If need new features of language - update PHP version.

> * Can't extend from specific rule (`Number` for example) to override just this property. Can be solved with extending from base `Rule` / composition, but isn't it over-complication?
Seems, this case is very specified. For specified cases create new class via composition is OK.
