### ISSUE TITLE
Nested rule doesn't specify a field with error

### ISSUE THREAD

**Issue by a6colute** [yiisoft/validator#200]
### What steps will reproduce the problem?

Add to rules

          'body.shipping' => [
                Required::rule(),
                Nested::rule([
                    'phone' => [MatchRegularExpression::rule('/^\+\d{11}$/')],
                ]),
          ],

Apply rules to data like

  "shipping": {
       "phone": "+791069885651",
  },

### What is the expected result?

body.shipping.phone: Value is invalid.

### What do you get instead?

body.shipping: Value is invalid.

### Additional info

| Q                | A
| ---------------- | ---
| Version          | 1.0.?
| PHP version      | 
| Operating system |

**Comment by arogachev** [comment]
Not reproducible in validator scope. Moving it to forms - https://github.com/yiisoft/form/issues/195.
