### ISSUE TITLE
[Design] Validation rules interpretation

### ISSUE THREAD

**Issue by xepozz** [yiisoft/validator#213]
Imagine that you have a model with some validation. 

Model:
```php
class CreateUserDto
{
  #[String]
  #[Length(max: 20)]
  private $name;

  #[String]
  #[Length(max: 20)]
  private $surname;
}
```

You wrote API and you wanted to try it. 

Validation:
```php
$dto = new CreateUserDto($payload)
$validator->validate($dto)
```

Payload:
```json
{"name": "Dmitrii"}
```

You sent the payload and what would you want to get in response?

There are only two options:
1. Validation passed.
2. Validation failed.

If you want to explain your decision feel free to write comment.

You can vote by emoji:
👍 – validation passed.
👎 – validation failed.

**Comment by sagittaracc** [comment]
Cant even imagine why it would pass

**Comment by dikium** [comment]
> Cant even imagine why it would pass

I cant imagine why would not :) Surname is not required, name length is less than 20.. Why?

**Comment by sagittaracc** [comment]
> > Cant even imagine why it would pass
> 
> I cant imagine why would not :) Surname is not required, name length is less than 20.. Why?

Cuz it doesnt say that surname is optional, so it has to be something

**Comment by terabytesoftw** [comment]
> Debería pasar. Si necesita que se requiera alguna propiedad, debe agregarle una regla, de lo contrario es opcional.

Shouldn't it happen for raw data the surname property has no value, so how to check that it is string ?

**Comment by kamilov** [comment]
Isn't it easier to return a list of errors?
```php
interface ErrorListInterface
{
    /**
     * if true - validation was successful 
     */
    public function isEmpty(): bool;
    
    public function getErrors(?string $name = null): array;
}

```

**Comment by sagittaracc** [comment]
I am sorry i changed my mind, didnt know what dto is. Of course it should be optional by default. 100%.

**Comment by yiiness** [comment]
Required or not required(optional), that is the question!
Is it possible to make this behavior globally defined?
The default value is closer to someone - required (yii-wai), someone else.

**Comment by xepozz** [comment]
You shouldn't change you mind because of someone say you about another logic.

What is important for me, that it is how you "read" these code. You shouldn't keep package internal logic in your mind.

If you are reading and interpreting as "should fail" but after test you understand that it should pass because of internal logic of the package, it's bad for me at least.

**Comment by bizley** [comment]
> Is it possible to make this behavior globally defined?

It would be easy to allow adding rule class-wide with attribute just above the class that would work for all properties but I don't know if this would be worth to do since:
1. Devs could easily do it by themselves.
2. It would rather be something used rarely (must be the reason why Symfony is not providing such constraints out-of-the-box).

**Comment by Nex-Otaku** [comment]
Fields should be **required** by default and **optional** with attribute #[Optional]

Good design is strict by defaut and less strict if you explicitly define it as less strict.

Consider example:

```
function setCache(string $key, string $value, int $seconds)

function setCache(string $key, string $value, ?int $seconds)
```

First method is more strict. It forces you to give lifetime seconds of cache item every time you call the method.

Second method is less strict. It allows you to call without passing value, so assuming lifetime is some default.

We made it less strict by explicitly adding "?" sign, so showing that there are MORE ways to call it, passing or not passing third parameter.

So it is logical to follow same convention for other places as well, such as validation definitions.

Strict (required) by default, less strct (optional) if defined explicitly with #[Optional]

**Comment by tomaszkane** [comment]
> Fields should be **required** by default and **optional** with attribute #[Optional]

So how I can set default cache time? I really don't line repeat i any `setCache()` third parameter who is always same.

**Comment by bizley** [comment]
> Fields should be required by default and optional with attribute #[Optional]

I could follow that design if this would be forced by the package but I would never design it like that because this is mixing the validation layer with the data layer (required in data layer would look like `private string $property;` - optional would look like `private ?string $property = null;`)

**Comment by yiiness** [comment]
> Fields should be required by default and optional with attribute #[Optional]

By default, this should be the case, but for the sake of more flexible compatibility with yii2, this property should be defined globally (it should be possible to invert this behavior).

**Comment by sagittaracc** [comment]
> You shouldn't change you mind because of someone say you about another logic.
> 
> What is important for me, that it is how you "read" these code. You shouldn't keep package internal logic in your mind.
> 
> If you are reading and interpreting as "should fail" but after test you understand that it should pass because of internal logic of the package, it's bad for me at least.

I didnt change my mind because of someone else. I did because now i have read the dto concept. It is some object you exchange between application parts, right? So it is all on me to decide what object params is required. I expect it to be optional by default this way.

**Comment by Nex-Otaku** [comment]
> > Fields should be required by default and optional with attribute #[Optional]
> 
> I could follow that design if this would be forced by the package but I would never design it like that because this is mixing the validation layer with the data layer (required in data layer would look like `private string $property;` - optional would look like `private ?string $property = null;`)

No. 

We can create this object with or without property "name" or "surname" just fine. It would be initialized by null values.

To force checks of attributes we must call them via constructor or create DTO with some factory etc.

**Comment by Nex-Otaku** [comment]
I agree with Dmitrii that expected behavior is the most important.

We should NOT follow rule "strict by default" if it is unexpected for developers. Usability means more than beauty )

As I see in Laravel request validation, there is a convention that all fields are optional by default and are casted to NULL.

Required fileds in Laravel request validator should be explicitly defined with word "required".
```php
$request->validate([
                       'name' => 'required|max:20',
                       'surname' => 'required|max:20',
                   ]);
```

So there is at least one popular framework that defaults to optional request parameters in validation.

Maybe we should follow this and do the same )

**Comment by tomaszkane** [comment]
Yii2 default behavior also is optional by default: https://www.yiiframework.com/doc/api/2.0/yii-validators-validator#$skipOnEmpty-detail

**Comment by mamadza** [comment]
if I understand well,  assume we have 12 property and two of them have to be required in this approach we need to tell all other fields not required

**Comment by vstokarev** [comment]
Why not use typing to let framework know whether we want any particular attribute to be required or not? Imagine we change the example above like this:

```php
class CreateUserDto
{
  #[Length(max: 20)]
  private string $name;

  #[Length(max: 20)]
  private ?string $surname;
}
```

Now if you parse the payload you mentioned (`{"name": "Dmitrii"}`) it will not cause any trouble and validator will assign `null` to `surname`, because it's nullable and the value is not specified in the payload.

But if you change `private ?string $surname;` to `private string $surname;` validation will fail.

Also, for input models like this it might be interesting to use readonly properties to avoid the need to create getters.
```php
class CreateUserDto
{
  #[Length(max: 20)]
  public readonly string $name;

  #[Length(max: 20)]
  public readonly ?string $surname;
}
```
But in this case all initialisation must be done in constructor (which is probably fine for input models).

**Comment by BoShurik** [comment]
@vstokarev if you pass `{"name": 1337}` you'll get an exception instead of validation error

**Comment by IStranger** [comment]
In the case of `{"name": "Dmitrii"}` the property `$surname;` remains uninitialized. So validation should pass. Optional property is default behavior.

**Comment by mikk150** [comment]
> Why not use typing to let framework know whether we want any particular attribute to be required or not? Imagine we change the example above like this:
> 
> ```
> class CreateUserDto
> {
>   #[Length(max: 20)]
>   private string $name;
> 
>   #[Length(max: 20)]
>   private ?string $surname;
> }
> ```
> 
> Now if you parse the payload you mentioned (`{"name": "Dmitrii"}`) it will not cause any trouble and validator will assign `null` to `surname`, because it's nullable and the value is not specified in the payload.
> 
> But if you change `private ?string $surname;` to `private string $surname;` validation will fail.
> 
> Also, for input models like this it might be interesting to use readonly properties to avoid the need to create getters.
> 
> ```
> class CreateUserDto
> {
>   #[Length(max: 20)]
>   public readonly string $name;
> 
>   #[Length(max: 20)]
>   public readonly ?string $surname;
> }
> ```
> 
> But in this case all initialisation must be done in constructor (which is probably fine for input models).

I like the idea(I do not, but I am willing to change)

but what if I need it to be required based on other field response?

**Comment by vstokarev** [comment]
> @vstokarev if you pass `{"name": 1337}` you'll get an exception instead of validation error

Correct, validation should fail in this case. If you would like validator to be "softer" then a class-level attribute can be added to a model, something like this:

```php
#[AutoTypeConversion]
class CreateUserDto
{
  #[Length(max: 20)]
  public readonly string $name;

  #[Length(max: 20)]
  public readonly ?string $surname;
}
```

In this case validator could "forgive" some type inconsistencies (i.e. convert integers or floats to string and assign them to appropriate properties of the model).

**Comment by vstokarev** [comment]
> In the case of `{"name": "Dmitrii"}` the property `$surname;` remains uninitialized. So validation should pass. Optional property is default behavior.

I would rather set `surname` to null if it is optional. I find it more convenient to deal with nulls than unitialized values. But it's just me.

**Comment by vstokarev** [comment]
> I like the idea(I do not, but I am willing to change)
> 
> but what if I need it to be required based on other field response?

If the value is conditionally required that apparently it must be optional. In this case the appropriate attribute must be added in order to check requirement conditions.

```php
class CreateUserDto
{
  #[Length(max: 20)]
  public string $name;

  #[Length(max: 20)]
  #[RequireWhen(fn(CreateUserDto $model) => $model->name == 'mike')]
  public ?string $surname;
}
```

**Comment by vstokarev** [comment]
Also, custom validators can be implemented as class methods. Look at how they made it in Python package called `pydantic`: https://pydantic-docs.helpmanual.io/usage/validators/

In our case it could be something like
```php
class CreateUserDto
{
  #[Length(max: 20)]
  public string $name;

  public int $age;

  #[Length(max: 20)]
  public ?string $surname;

  #[Validator('name')]
  private function verifyName(string $value): void
  {
    // Do your value check here and throw an exception if it fails
  }
}
```

But I guess what I'm proposing is actually a bit bigger than just a validator. It is rather something a data modeller. But honestly this is exactly what I personally would like to see.

**Comment by hyncica** [comment]
> Why not use typing to let framework know whether we want any particular attribute to be required or not? Imagine we change the example above like this:
> 
> ```
> class CreateUserDto
> {
>   #[Length(max: 20)]
>   private string $name;
> 
>   #[Length(max: 20)]
>   private ?string $surname;
> }
> ```
> 
> Now if you parse the payload you mentioned (`{"name": "Dmitrii"}`) it will not cause any trouble and validator will assign `null` to `surname`, because it's nullable and the value is not specified in the payload.

How would you treat situation like this:
```php
$dto = new CreateUserDto(['name' => '', 'surname' => 'whatever']);
```
The empty string is valid string value but it wouldn't pass current `Require` validation. It's reasonable to expect that empty value wouldn't pass Require validation. Yet, null and empty string are different values and might have different meaning. If we are talking about form inputs there is difference between "field is not in post data" and "field is in post data but contains empty string".

Personally, I believe that when it comes to validation only rules that are **explicitly specified** should be applied. No rules should be applied by default or based on property type. The reason is pretty simple: it's easy to add the rule when you need it. But, it's hard to avoid rule added implicitly if you don't need it.

**Comment by samdark** [comment]
So, it seems, majority are expecting "optional by default".
