### ISSUE TITLE
Allow validation methods like "validate{$fieldName}" similar to Django, DRF, Pydantic, etc.

### ISSUE THREAD

**Issue by arogachev** [yiisoft/validator#223]
Extracted from #213, see https://github.com/yiisoft/validator/issues/213#issuecomment-1099517117.

Suggested by @vstokarev.

**Comment by samdark** [comment]
Can't it be achieved by callback rule with specifying `[$this, 'validateBla']`? Because using a name convention is a bit magical...

**Comment by samdark** [comment]
Callback cannot be used via attributes so it may make sense to support a kind of shortcut. I'm not sure about its syntax though.

**Comment by samdark** [comment]
I don't like it since it's not clear from `$name` rule attributes that a custom method will be applied as well. I'd prefer a callback being able to call named methods:

```php
class DTO
{
  #[Length(min: 3)]
  #[Callback(method: 'validateName')]
  private $name;
```

**Comment by xepozz** [comment]
`#[Validate(property: name)]`?

**Comment by xepozz** [comment]
Actually `name` or `property` is quit useful thing, because you may have different naming convention in the API contract and program code base. For example, `user_id` is in the contract and `userId` in the code base may make you write linter's suppressions if you use it.
The same situation with virtual properties. You may want to answer a bit more that just as the structure has. But making a new property may look wildly because you have property, but it's not a real property.

**Comment by xepozz** [comment]
```php
class Post
{
    #[HasLength(max: 100, name: 'long_desc')]
    private $longDesc;
    #[Each([new Image()], name: 'images')]
    private $images;
    #[Count(name: 'image_count')]
    private $imagesCount; // but it's not exist in API contract

    #[Validate(name: 'images_count')] // it's more clear because I don't see any fields here
    public function validateImagesCount()
    {
        // ...
    }

    #[Validate(name: 'long_desc')] // here we may append error list of `long_desc` property if needed
    #[HasLength(max: 100)]
    public function getLongDesc()
    {
        return /* strip some characters and check again */ $this->longDesc;
    }
}
```

**Comment by samdark** [comment]
Decided to implement https://github.com/yiisoft/validator/issues/223#issuecomment-1189868005.

https://github.com/yiisoft/validator/issues/223#issuecomment-1190613219 is cool but complicated.

**Comment by xepozz** [comment]
actually it's partially implemented in the form package
