### ISSUE TITLE
Add detailed annotation for return value of `Rule::getOptions()`

### ISSUE THREAD

**Issue by vjik** [yiisoft/validator#225]
For example. `Boolean` rule:

```php
/**
 * @psalm-return array{
 *   trueValue: mixed,
 *   falseValue: mixed,
 *   strict: bool,
 *   message: string,
 * }
 */
public function getOptions(): array
{
	return array_merge(parent::getOptions(), [
		'trueValue' => $this->trueValue,
		'falseValue' => $this->falseValue,
		'strict' => $this->strict,
		'message' => $this->getFormattedMessage(),
	]);
}
 ```

**Comment by Sergiayn** [comment]
I want to do it

**Comment by arogachev** [comment]
The current intended usage is for frontend only. After discussion we decided to not add it for now.

**Comment by rustamwin** [comment]
> The current intended usage is for frontend only and maybe for tests. So after discussion we decided to not add it for now.

https://github.com/yiisoft/form/blob/master/src/Field/Textarea.php#L221

**Comment by arogachev** [comment]
@rustamwin Thanks. https://github.com/yiisoft/form/pull/226
