### ISSUE TITLE
Nested structure validation

### ISSUE THREAD

**Issue by samdark** [yiisoft/validator#23]
It would be great to be able to specify validation for nested structures such as arrays or JSON.

See https://yiiframework.ru/forum/viewtopic.php?f=38&t=51463

**Comment by demonking** [comment]
Could you post an example?

**Comment by samdark** [comment]
Input:

```php
$_POST = [
   'id' => 42,
   'name' => 'Nested structure validation',
   'tags' => ['nested', 'validation'],
];
```

Need to validate that each item in tags is a string with at least 3 characters.

**Comment by samdark** [comment]
That is now possible with `Each` validator but I'm not sure it will work well for more complicated structures.

**Comment by demonking** [comment]
i will test , and when needed implement it

**Comment by SOHELAHMED7** [comment]
@Insolita has created a amazing package (https://github.com/Insolita/yii2-array-structure-validator) for similar thing in Yii2. We can re-use it.
