### ISSUE TITLE
Add composite rule so as not to duplicate `skipOnEmpty`, `skipOnError` and `when` 

### ISSUE THREAD

**Issue by vjik** [yiisoft/validator#234]
For example, instead of:

```php
'name' => [
	new Required(when: fn() => $this->useName),
	new HasLength(min: 1, max: 50, skipOnEmpty: true, when: fn() => $this->useName),
],
```

use:

```php
'name' => [
	new CompositeRule(
		rules: [
			new Required(),
			new HasLength(min: 1, max: 50, skipOnEmpty: true),
		]
		when: fn() => $this->useName,		
	),
],
```

**Comment by samdark** [comment]
It's already there: https://github.com/yiisoft/validator/blob/master/src/Rule/GroupRule.php

**Comment by samdark** [comment]
https://github.com/yiisoft/validator#grouping-multiple-validation-rules

**Comment by samdark** [comment]
Or do you mean something else?

**Comment by vjik** [comment]
> It's already there: https://github.com/yiisoft/validator/blob/master/src/Rule/GroupRule.php

No. `GroupRule` is abstract.

> https://github.com/yiisoft/validator#grouping-multiple-validation-rules

`RuleSet` house is no more.

Need rule that implement `BeforeValidateInterface` and applying all nested rules.
