### ISSUE TITLE
Phone validator

### ISSUE THREAD

**Issue by samdark** [yiisoft/validator#24]
Would be good to have international phone validator.

Input: +7 454 545-44-44, +74545454444, +7 (454)545-4444

Algorithm:

1. Check if phone starts with `+`.
2. Take rest of the string, remove space, `-`, `(`, `)`. Check if string is numeric.

**Comment by machour** [comment]
`+` can be substituted by `00` (0033612345678 and +33612345678 are the same phone number)

**Comment by samdark** [comment]
Nope. That's country-specific.

**Comment by SilverFire** [comment]
As far as I know, [libphonenumber by Google](https://github.com/google/libphonenumber) is the most correct phone validator implementation. There is a PHP port [libphonenumber-for-php](https://github.com/giggsey/libphonenumber-for-php) so I'd prefer using it.

**Comment by samdark** [comment]
Seems to be out of scope of general validation library.
