### ISSUE TITLE
Mark RuleHandlerInterface::validate() method as unavailable to direct call

### ISSUE THREAD

**Issue by xepozz** [yiisoft/validator#242]
The main thought is to tell users not to call the method directly and use `ValidatorInterface` and its method `validate` with passing `$value` and `$rules` separately or with using _attributes_ over `$value` instead.

Even if someone wants to check only one rule, use `Validator`.
I've tried to collect advantages:
1. The result might be different between `Validator` and each `Handler`. Something might be added or removed inside `Validator`. Some decorators or some logic to take more control over validators, validating values and context.
2. In _dev_ mode `Validator` may dump performance timings, values and results of validation into debugger

**Comment by samdark** [comment]
This mark will be phpdoc only so won't really forbid calling it. Also, in some cases it's useful. For example, when there's a complicated validation process such as validating MX record for an email, it is handy to reuse it for assertions.

**Comment by xepozz** [comment]
In your case you may separate the check into another class and call it when you want

**Comment by vjik** [comment]
Additionaly, this allow move prevalidate logic and message formatting from rule handlers to validtor.

**Comment by samdark** [comment]
OK. That seems to be a good thing.

**Comment by samdark** [comment]
1. Mark standard handler's validate() as `@internal`.
2. Mention in readme that handlers should not be used without validator.
