### ISSUE TITLE
Got misunderstanding configuring rules over attributes

### ISSUE THREAD

**Issue by xepozz** [yiisoft/validator#243]
I've found a few problems:
1. All rules don't have REPEATABLE flag.
2. `Each`, `Nested` rules (but suddenly not `Group`, `Composite`) don't work at all without additional attributes.

We have great [example](https://github.com/yiisoft/validator/blob/1f21d2edca9373e90cfaeb231dc907c31b8256f3/tests/DataSet/AttributeDataSetTest.php#L22) with composition of attributes, but configuring an inheritance have to be different.

[How it's configuring now.](https://github.com/yiisoft/validator/blob/b7ec94dfa46762b73a45df396c5bbb7e38cfed17/tests/Data/Charts/ChartsData.php#L11)

How it should be configured:
```php
final class ChartsData
{
    #[Each(
        rules: [
            new HasMany(Chart::class),
        ],
        incorrectInputMessage: 'Custom message 1.',
        message: 'Custom message 2.'
    )]
    private array $charts;
}
```

But `HasMany` and `HasOne` aren't `Rules`, so they can't be passed into `rules`. We need to make another rule something like "as from $classname". The implementation and name are up to developer.

I'll make a pr with tests those should pass

**Comment by xepozz** [comment]
@arogachev would you like to do it?

**Comment by arogachev** [comment]
@xepozz Sorry, I don't understand it fully. Why we need to pass `HasMany` in rules like that?

**Comment by samdark** [comment]
What's "REPEATABLE flag"?

**Comment by xepozz** [comment]
> What's "REPEATABLE flag"?

https://www.php.net/manual/en/language.attributes.classes.php

**Comment by xepozz** [comment]
> @xepozz Sorry, I don't understand it fully. Why we need to pass `HasMany` in rules like that?

Not HasMany, but another rule that can be "reference" or embedding for class

**Comment by rustamwin** [comment]
> All rules don't have REPEATABLE flag.

Is there any case for this?

**Comment by xepozz** [comment]
If array-like configuration supports multiple same validators attributes should support too.
Just for you:
```php
#[Number(min: 18, when: fn() => ...)]
#[Number(min: 21, when: fn() => ...)]
private $age;
```

Or you may want to use some composite rule and make one of its rules stronger:
```php
class CompositeRule
{
    public function getRules() {
        return [
            new Number(min: 18, when: fn() => ...),
            ...
        ];
    }
}

#[CompositeRule]
#[Number(min: 21, when: fn() => ...)]
private $age;
```

**Comment by arogachev** [comment]
Now it's more clear, but arrow functions are not supported in attributes.

**Comment by xepozz** [comment]
Sure, that's not a problem.
