### ISSUE TITLE
Make validation context mandatory

### ISSUE THREAD

**Issue by rustamwin** [yiisoft/validator#247]
### What steps will reproduce the problem?
Must be check every time according to stat analysis
### What is the expected result?
Direct use without checking
### What do you get instead?
Need to use null-safe operator

### Additional info
In fact, the context is always passed in the validator.
https://github.com/yiisoft/validator/blob/b69f59b20758306296b7cd855d3f8a3ee5cf8a99/src/Validator.php#L41

**Comment by vjik** [comment]
If we deny use rules without `Validator` (see https://github.com/yiisoft/validator/issues/242), then context will be is mandatory.

**Comment by samdark** [comment]
Decided to do it.
