### ISSUE TITLE
Port Embedded attribute as a rule

### ISSUE THREAD

**Issue by xepozz** [yiisoft/validator#259]
In #249 we were instoduced [Embedded](https://github.com/yiisoft/validator/blob/a679e36848aa88957718f517cb54e1fd9c5aee04/src/Attribute/Embedded.php) attribute that can only work as `Attribute`. 
After some discussion we decided to make it as `Rule` too.

Some point to further implementation:
1. `Embedded` **rule** should work only with `\Yiisoft\Validator\RulesProviderInterface`
2. `Embedded` **attribute** should continue work with any objects that has attributes

**Comment by arogachev** [comment]
Closing because there is no more `Embedded` rule.
