### ISSUE TITLE
Does IPv6 expand make sense in the IP rule?

### ISSUE THREAD

**Issue by kamarton** [yiisoft/validator#27]
### What steps will reproduce the problem?

Is the input value overwritten in yii3 meaningful?

https://github.com/yiisoft/validator/blob/725fdfc3c18d8ef0fee3ed80fd73abe417620d77/src/Rule/Ip.php#L100-L104

similar:
https://github.com/yiisoft/validator/blob/725fdfc3c18d8ef0fee3ed80fd73abe417620d77/src/Rule/Ip.php#L86-L94

| Q                | A
| ---------------- | ---
| Version          | 3.0.x-dev
| PHP version      | -
| Operating system | -

**Comment by samdark** [comment]
Related to #21

**Comment by kamarton** [comment]
> No. These do not make sense. Yii 3 validation should not change values.

Thanks

> Related to #21

oh, it's already work in progress.

**Comment by samdark** [comment]
It is stale.

**Comment by kamarton** [comment]
> It is stale.

Then I can create a PR for the `Ip` class and tests?

**Comment by samdark** [comment]
Yes.
