### ISSUE TITLE
Validator requires one attribute and cannot see the whole model

### ISSUE THREAD

**Issue by kamarton** [yiisoft/validator#28]
### What steps will reproduce the problem?

In yii2, it was easy to access any of the model's attributes. In yii3, In Yii3 this option seems to me not feasible.

https://www.yiiframework.com/doc/guide/2.0/en/input-validation#standalone-validators

https://github.com/yiisoft/validator/blob/725fdfc3c18d8ef0fee3ed80fd73abe417620d77/src/Validator.php#L36

This issue also affects the `Result` class because it is not suitable for adding errors to an attribute.

### What is the expected result?

I get the whole dataset in an extra parameter, and change return type to `ResultSet`

```php
public function validate($value, DataSetInterface $dataSet): ResultSet
// or yii2 style
public function validate(?string $attribute, DataSetInterface $dataSet): ResultSet
```

https://github.com/yiisoft/validator/blob/725fdfc3c18d8ef0fee3ed80fd73abe417620d77/src/Rule.php#L10

https://github.com/yiisoft/validator/blob/725fdfc3c18d8ef0fee3ed80fd73abe417620d77/src/Result.php#L19

https://github.com/yiisoft/validator/blob/725fdfc3c18d8ef0fee3ed80fd73abe417620d77/src/ResultSet.php#L12

usage:

```php
[
  /* numeric index -> attribute=null */ (new MyComplexRule())->moreParameters()...
]
```

### What do you get instead?

```php
[
  'notRelevantAttributeName' => (new MyComplexRule())->with($this /* or $dataset ??*/)->moreParameters()...
]
```

But in this case, I have no way of returning an arbitrary attribute error of the model.

### Additional info

Also, to keep the benefits of the current solution, the `Rule` class should be somehow allow the` Result` class to be used internally in simpler cases.

### Use case

I need to check for additional attributes depending on a type attribute.

| Q                | A
| ---------------- | ---
| Version          | 3.0.x-dev
| PHP version      | -
| Operating system | -

**Comment by kamarton** [comment]
Even better, if `ResultSet` is part of the parameters: #29 
```php
public function validate(?string $attribute, DataSetInterface $dataSet, ResultSet $resultSet): ResultSet /* return for override? */
```

**Comment by samdark** [comment]
How would that work for cases described in readme?

**Comment by kamarton** [comment]
> How would that work for cases described in readme?

```php
class CountryValidator extends Validator
{
    public function validateAttribute($model, $attribute)
    {
        if($model->type === 'any') {
           $this->addError($model, 'fieldA', '....');
        } else {
           $this->addError($model, 'fieldA', '....');
           $this->addError($model, 'fieldB', '....');
        }
    }
}
```

**Comment by samdark** [comment]
And the rest of the cases?

**Comment by kamarton** [comment]
> And the rest of the cases?

I have access to everything in the example code method:
- I can add an error message to any attribute
- access to any attribute of the model

**Comment by samdark** [comment]
There are multiple examples:

1. Validating a single value
2. Validating a set of data
3. Grouping common validation rules into rule sets

**Comment by kamarton** [comment]
> 2. Validating a set of data
```php
class CountryValidator extends Validator
{
    // check multiple attribute at one context
    public function validateAttribute($model, $attribute)
    {
	if($model->fieldA && $model->fieldB) {
           // together not allowed
           $this->addError($model, 'fieldA', 'together not allowed');
           $this->addError($model, 'fieldB', 'together not allowed');
	}
    }
}
```

**Comment by demonking** [comment]
> Even better, if `ResultSet` is part of the parameters: #29
> 
> ```
> public function validate(?string $attribute, DataSetInterface $dataSet, ResultSet $resultSet): ResultSet /* return for override? */
> ```

Like decided 844477

> Even better, if `ResultSet` is part of the parameters: #29
> 
> ```
> public function validate(?string $attribute, DataSetInterface $dataSet, ResultSet $resultSet): ResultSet /* return for override? */
> ```

Validator are not allowed to manipulate data

https://forum.yiiframework.com/t/saving-or-killing-non-validation-in-validators/126086

**Comment by kamarton** [comment]
> This wouldn't be a validator anymore, it seems more like an expression or something similar

That's just the rule. It is normal for a form to contain attributes that are related to one another. For example in sign up form with password and password re, or email and email re.

**Comment by kamarton** [comment]
More problem in code complexity for example delivery address, with more sub fields.

Here, too, the problem is with an alternative delivery address option:
- or all fields are left blank
- or, if one is completed, all are required

In addition, the code complexity issue is:
```php
// If the attributes of the dataset cannot be accessed in the rule
[
  'anyattribute' => new Any()->...,
  'delivery_country' => new HasLength()->..
  'delivery_postal_code' => new HasLength()...
  'delivery_...' => ...
]
// A billing address and a shipping address must be provided.
[
  'anyattribute' => new Any()->...,
  'delivery_country' => new HasLength()->..
  'billing_country' => new HasLength()->..
  'delivery_postal_code' => new HasLength()...
  'billing_postal_code' => new HasLength()...
  'delivery_...' => ...
  'billing_...' => ...
]
```

by issue:
```php
[
  'anyattribute' => new Any()->...,
  /* attribute is not relevant */ (new Address())->attributePrefix('delivery_'), 
  /* attribute is not relevant */ (new Address())->attributePrefix('billing_'), 
]

class Address {
  ...
  public function attributePrefix(..);
  ...
  public function validateValue(?string $attribute, DataSetInterface $dataSet, ResultSet $resultSet): ResultSet {
    if($this->optional && empty($dataSet->getValue($this->prefix.'country')) && ....) {
      return $resultSet;
    }
    $countryResult = (new HasLength())->min...->validateValue($dataSet->getValue($this->prefix.'country'));
    $resultSet->addResult($this->prefix.'country', $countryResult);
    ...
    return $resultSet;
  }
}
```

**Comment by demonking** [comment]
> > This wouldn't be a validator anymore, it seems more like an expression or something similar
> 
> That's just the rule. It is normal for a form to contain attributes that are related to one another. For example in sign up form with password and password re, or email and email re.

This seems like a use-case for scenarios :)

**Comment by samdark** [comment]
Correct, no screnarios are planned.

**Comment by demonking** [comment]
@samdark what is then your opinion for this issue?

**Comment by samdark** [comment]
No final opinion yet. That's fairly typical use case for validation in Yii 2 and, no doubt, there will be similar problem to solve in Yii 3 projects:

1. If checkbox A is checked, validate field B else ignore it.
2. One of A, B, C should be filled.

etc.

**Comment by Insolita** [comment]
I'm agree that in practical we often need to make validation against attributes that  depends on values of another attributes. It often happens when we check data from complex forms by api  
And when we validate nested json structure we need to be flexible with attribute that will be target for error message 

> What's not clear is where/how to do this type of compound validation.

In yii2 we have "when" condition and can create rules like

```php
return [
[['ip'], 'ip', 'ipv6'=>false, 'when'=>function($model){return $model->allowIpv6===false;}],
[['ip'], 'ip', 'ipv6'=>true, 'when'=>function($model){return $model->allowIpv6===true && !$model->ipv6Only;}],
[['ip'], 'ip', 'ipv6'=>true, 'ipv4'=>false,  'when'=>function($model){return $model->allowIpv6===true && $model->ipv6Only===true;}]
]
```
Why not do something similar

```php
$validator = new Validator([    
   //...
   'allowIpv6'=>[new Boolean()],
   'onlyIpv6'=>[new When(function(DataSetInterface $data){
             if($data->getValue('allowIpv6') == false) {
                 return (new CompareTo(false)->asBoolean());
             }
             return new Boolean(), 
    })],
    'ip' => [
       new When(function(DataSetInterface $data){
         return (new Ip())->allowIpv6($data->getValue('allowIpv6'))
                    ->allowIpv4(!$data->getValue('onlyIpv6'));
      });
    ],
]);
```

**Comment by Insolita** [comment]
And for previous case something like
```php
$validator = new Validator([    
   //...
   'fieldA' =>[new InRange(['X', 'Y', 'Z'])],
   new ConditionalRules(function(DatasetInterface $data){
        if($data->getValue('fieldA') == 'X'){
             return RuleSetForX::get();
       }
       //..
       return RuleSetForZ::get();
})
])
```

**Comment by demonking** [comment]
I prefer classes instead of in line functions. For small validations it's fine, aber you geht some functions, it will bloat up the code.

When we will use classes for this, then it would be similar with the solution from @kamarton

**Comment by samdark** [comment]
> Why not do something similar

In present state Rule and Rules aren't bound to data set. They work with individual value.

**Comment by samdark** [comment]
There are two use cases for validation:

1. Individual values.
2. Data sets.

Yii 2 was data set oriented and it wasn't convenient to use validation with individual values via fake dynamic model.

**Comment by Insolita** [comment]
> In present state Rule and Rules aren't bound to data set. They work with individual value.

In my cases i dont't boud dataset in rule directly. It can be bounded by wrapper and resolved inside
 Validator->validate(), but ok... 

> There are two use cases for validation:
Individual values.
Data sets.
Yii 2 validation was data set oriented and it wasn't convenient to use validation with individual values via fake dynamic model.

I look on validation from point of applicable context also. In yii2 we have models with set of rules and different scenarios.

At now, especially with orm, we probably will validate request before fill model. So we can do it in controller or with separated validation classes like AuthRequestValidation, RegistrationRequestValidation, CreatePostValidation, EditPostValidation... And probably we will need some business-rule-scoped validators/or rule/or rulesets that should be reusable in different requests
For ex. Title - should be string, trimmed, title cased, and limited with 150 chars, Phone should be started with +, numeric, and probably limited with only allowed country codes, like only russian and ukraine. Address - is set of fields like country, street, code etc. And that should be reusable in different request context.  And i don't see these ability with current approach.  If i create separated Validator instances for all, next i must additionaly combine result-sets. If i create ti as rules - i haven't access to additional data.  
So at now i feel that something is missing.  Or you mean different use approach that is not clear for me

**Comment by samdark** [comment]
> new When(function(DataSetInterface $data){

How would `$data` be passed?

**Comment by Insolita** [comment]
As i see in https://github.com/yiisoft/validator/blob/master/src/Validator.php#L31

```php
 public function validate(DataSetInterface $dataSet): ResultSet
    {
        $results = new ResultSet();
        foreach ($this->attributeRules as $attribute => $rules)
        {
           if ($rules instanse of When){ 
              $rules = $rules->resolve($dataSet); 
           }
            $results->addResult($attribute, $rules->validate($dataSet->getValue($attribute)));
        }
        return $results;
    }

class When
{
      private $rule;
      public function __construct(callable $rule){ $this->rule = $rule;}
      public function resolve(DataSetInterface $data){
         return $this->rule($data);
    }
}
```

**Comment by kamarton** [comment]
> There are two use cases for validation:
> 
> 1. Individual values.
> 2. Data sets.

I think it would be enough for the ResultSet to get to the `Rules` and (or?)` Rule` classes. The Individual value could be treated as a data set. At this point, the handling of the variable will remain current, but errors could be applied to any attribute based on the dataset.

**Comment by samdark** [comment]
@Insolita that brings two possible use-cases into Rule class. If we're going to do that, Yii 2 concept fits a bit better.

@kamarton 

> The Individual value could be treated as a data set. At this point, the handling of the variable will remain current, but errors could be applied to any attribute based on the dataset.

Applying errors to any attribute is not the only thing that is missing. That's only point 3 from https://github.com/yiisoft/validator/issues/28#issuecomment-548809148

**Comment by kamarton** [comment]
> Applying errors to any attribute is not the only thing that is missing. That's only point 3 from #28 (comment)

The return value must be changed to `ResultSet`. And the `ResultSet` must be modified so that all errors can be retrieved, with or without attributes. The `Result` class should be merged with ` ResultSet`.

```php
$resultset = (new Integer())->max(100)->validate(100);
$resultset->isValid();
$resultset->getErrors();

$resultset = (new Complex())->...->validate($dataset);
$resultset->isValid();
$resultset->getErrors();    // all erros
$resultset->getErrors($attribute);    // errors by attribute
```

**Comment by samdark** [comment]
@kamarton That's OK but how do you plan getting data set into Rule?

**Comment by kamarton** [comment]
> @kamarton That's OK but how do you plan getting data set into Rule?

- add `Rule::isSupportDataSet():bool`
- modify `Validator`

https://github.com/yiisoft/validator/blob/4d504bce7e81f3823831bf163a013f92c174187a/src/Validator.php#L31-L39

With the `Rules` class, I don't know how. Special cases could be treated so that only classes from the `Rules` inheritance can use the dataset. This is also logical, because in this case, more than one rule applies.

```php
class Address extends Rules
{
  public function isSupportDataSet() {    <---- maybe put it here ??
    return true;
  }
}
```

This solution implies that `Validator::$attributeRules` cannot have an attribute index. The attribute name must be moved one dimension deeper.

https://github.com/yiisoft/validator/blob/4d504bce7e81f3823831bf163a013f92c174187a/src/Validator.php#L8-L13

**Comment by samdark** [comment]
After thinking more of it, I came to conclusion that it doesn't make sense to have validator that works for a single value. That is the job for assertions.

**Comment by samdark** [comment]
A validator for a single value is basically assertion. If we can have both that would be good but I suspect that it may complicate library too much.

**Comment by kamarton** [comment]
> A validator for a single value is basically assertion. If we can have both that would be good but I suspect that it may complicate library too much.

I think this is mandatory rather than optional. For example, if I make my own rule that uses additional rules, I will usually validate single values.

**Comment by kamarton** [comment]
@samdark  needed for the alpha version?

**Comment by samdark** [comment]
Yes.

**Comment by demonking** [comment]
@samdark when will be the freeze for alpha?
Would like to help with the validators, so i can port the logic from yii2 ->yii3 in the next days

**Comment by samdark** [comment]
By the end of the month or around it.

**Comment by kamarton** [comment]
Also consider the scenario option when designing. #38
