### ISSUE TITLE
For `Equal` rule add boolean type of value

### ISSUE THREAD

**Issue by vjik** [yiisoft/validator#281]

**Comment by samdark** [comment]
Would you please elaborate?

**Comment by vjik** [comment]
I need check that user select checkbox "I agree".

In form model has property `bool $agree = false` and need rule for check `$agree` on true. 

Maybe create rule `IsTrue` - it is will be convient for this case.

**Comment by arogachev** [comment]
User agreements are quite common, I am also for having this, especially if `Compare` rule was already split into separate ones. Is `true` enough? Can't remember cases when only `false` is needed.
