### ISSUE TITLE
yii2 Validator::$skipOnError not implemented

### ISSUE THREAD

**Issue by kamarton** [yiisoft/validator#29]
### What steps will reproduce the problem?

https://www.yiiframework.com/doc/api/2.0/yii-validators-validator#$skipOnError-detail

Yii2 gave you the option to skip validations if an error was already registered. This is particularly important in terms of performance.

For example, if check a string for both length and uniqueness in a database, then obviously if the length is not good then the uniqueness test does not make sense.

### What is the expected result?

The rules should be skippable.

### What do you get instead?

All rules are executed.

| Q                | A
| ---------------- | ---
| Version          | 3.0.x-dev
| PHP version      | -
| Operating system | -

**Comment by samdark** [comment]
Could be added to `Rules` and `Validator`.
