### ISSUE TITLE
Email validator with allowed and disallowed domains

### ISSUE THREAD

**Issue by kamarton** [yiisoft/validator#30]
### What steps will reproduce the problem?

It is often the case that I do not want to allow disposable email addresses. (https://www.minuteinbox.com)

### What is the expected result?

Support in the `Email` rule class.

```php
// If enable everything and removes:
(new Email())->domainFilters([
  '!farzan.ziyan@niickel.us', /* https://www.minuteinbox.com */
  '!*.de',
]);
// If disable everything and add:
(new Email())->domainFilters([
  '!*',
  'mybusiness.com',
]);
// callback
(new Email())->domainFilters([
  function($domain, $email) {
    // Downloaded a larger list from an external source
   return true/false;
  },
]);
```

### What do you get instead?

An additional rule is required eg. `MatchRegularExpression`.

| Q                | A
| ---------------- | ---
| Version          | 3.0.x-dev
| PHP version      | -
| Operating system | -

**Comment by samdark** [comment]
Sounds good.

**Comment by samdark** [comment]
But... can't it be currently implemented with `MatchRegularExpression`?

**Comment by samdark** [comment]
i.e.

```php
class NotDisposableEmailRules
{
    public function get(): array
    {
        return [
            (new MatchRegularExpression('@(niickel\.us|\.de|anothertempemail.com)$'))->not(),
            new Email()
        ];
    }
}
```

**Comment by kamarton** [comment]
> But... can't it be currently implemented with `MatchRegularExpression`?

Less comfortable, but also fully functional with regexp.

**Comment by samdark** [comment]
I'd keep Email validator itself simple since there's now an ability to easily combine rules for reuse.
