### ISSUE TITLE
The `Email` rule also checks the DNS A record, but this is incorrect for email sending

### ISSUE THREAD

**Issue by kamarton** [yiisoft/validator#34]
### What steps will reproduce the problem?

If the validation of the MX record was unsuccessful, it will attempt to verify the A record, but the verification of the A record will give false results and is incorrect.

https://github.com/yiisoft/validator/blob/4d504bce7e81f3823831bf163a013f92c174187a/src/Rule/Email.php#L86

If the MX entry fails, the mail sending will not work, regardless of the A record pointing somewhere. An MX record is an entry that points to an A record, but this A record itself is mostly completely independent of the A record in the domain of the email.

eg. yiiframework.com points to MX: mxb.cebe.cc.

```bash
$ dig yiiframework.com MX

; <<>> DiG 9.11.3-1ubuntu1.9-Ubuntu <<>> yiiframework.com MX
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 55535
;; flags: qr rd ra; QUERY: 1, ANSWER: 2, AUTHORITY: 0, ADDITIONAL: 1

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 65494
;; QUESTION SECTION:
;yiiframework.com.		IN	MX

;; ANSWER SECTION:
yiiframework.com.	3561	IN	MX	10 mxb.cebe.cc.
yiiframework.com.	3561	IN	MX	10 mxa.cebe.cc.

;; Query time: 0 msec
;; SERVER: 127.0.0.53#53(127.0.0.53)
;; WHEN: Sat Nov 02 13:17:57 CET 2019
;; MSG SIZE  rcvd: 92

```

### What is the expected result?

From DNS, check only the MX record.

### What do you get instead?

MX and A (ipv4) records are checked.

### Additional info

Yii2 comes from this [commit](https://github.com/yiisoft/yii2/commit/070bd9625cd157f8923c50c9064a9fc2fd5c443c), which is from https://github.com/yiisoft/yii2/issues/1246.

https://help.dnsmadeeasy.com/managed-dns/dns-record-types/mx-record/

| Q                | A
| ---------------- | ---
| Version          | 3.0.x-dev (starting with yii2)
| PHP version      | -
| Operating system | -

**Comment by samdark** [comment]
@cebe could you check it?

**Comment by cebe** [comment]
> https://help.dnsmadeeasy.com/managed-dns/dns-record-types/mx-record/

If you read the information on that link, you will see that the A record is relevant in case there are no MX records (first checkdnsrr call fails):

> If an MX record is missing for the domain, then the mail for the domain will normally be attempted to be delivered to the matching A record. So for the domain “yourdomain.com” if there were no MX records for “yourdomain.com” then the mail would be attempted to delivered to the apex/root record of “yourdomain.com”.

This is also explained in the SMTP RFC: https://tools.ietf.org/html/rfc5321#section-5

**Comment by kamarton** [comment]
@cebe correct answer, I didn't know about this opportunity, thanks!
