### ISSUE TITLE
Short declaration for validator initialization

### ISSUE THREAD

**Issue by xepozz** [yiisoft/validator#35]
How about to use static factory method `::init`, `::create`, `::new` or other for creating a validator?
For example we can use `Number::new()->min(10)` instead of `(new Number())->min(10)`.
Short declaration, it seems to me, is more graceful.

**Comment by kamarton** [comment]
is not shorter, this form is just an extra method.

**Comment by samdark** [comment]
As @kamarton said, these two are of almost equal length:

```php
Number::new()->min(10)
(new Number())->min(10)
``
