### ISSUE TITLE
Improve adding parameters for error formatting

### ISSUE THREAD

**Issue by arogachev** [yiisoft/validator#362]
Found during #352.

In many places parameters are added to error for further formatting (along the others, the most common are "attribute" and "value"):

https://github.com/yiisoft/validator/blob/c6159bf1bee37d67fb8ee735cf6196c1a9d48bad/src/Rule/CountHandler.php#L33-L39

While in reality the message doesn't even have placeholders with relevant names or doesn't have placeholders at all:

https://github.com/yiisoft/validator/blob/c6159bf1bee37d67fb8ee735cf6196c1a9d48bad/src/Rule/Count.php#L58

This causes appearance of escaped mutants. I handled it in #352 - we need to first add according placeholders to the message otherwise it will be useless / premature.

From the other side, there are might be some cases where these parameters could be useful. For example, maybe a user wants to reflect them in the error? A message can be customized in constructor, but passing parameters - can't. 

Then maybe add the most demanded parameters ("attribute", "value") on the upper level via validation context / etc.? Or allow to customize it in a more flexible way, specifying explicitly which parameters need to be added to the message?

**Comment by vjik** [comment]
Message and her parameters is defined in rule and handler. 

You are right, in default message parameter can be not used, but it can be in custom message.

I think we should:

1) describe parameters that pass to message in phpdoc of message property;
2) if parameter not use in default message then create test with custom message where parameter will be used.

**Comment by arogachev** [comment]
Docs added during work on #358. Tests were added earlier.

**Comment by arogachev** [comment]
Repeated code is handled locally, like this for example:

https://github.com/yiisoft/validator/blob/22adb7f67d3a8fd1c2a6cf68a3630f062c731cce/src/Rule/IpHandler.php#L188-L194

But I think it's OK for now.
