### ISSUE TITLE
dataset scenario

### ISSUE THREAD

**Issue by kamarton** [yiisoft/validator#38]
yii2 https://www.yiiframework.com/doc/guide/2.0/en/structure-models#scenarios

| Q                | A
| ---------------- | ---
| Version          | 3.0.x-dev
| PHP version      | -
| Operating system | -

**Comment by kamarton** [comment]
It may be enough to have an interface next to `DataSetInterface` If not `$dataset instanceof DataSetScenarioInterface` then the scenario branch can be ignored.

```php
interface DataSetScenarioInterface {
  function setScenario(?string $scenario=null):void;
  function getScenario(): ?string;
  function hasAttributeInScenario(string $attribute);
}
```

**Comment by samdark** [comment]
I'd not introduce scenarios at all. It's easy to create a compound validator now and reuse it and that's preferred since it's very hard to find/fix mistake when there are >50 validation rules for multiple scenarios.

**Comment by kamarton** [comment]
Do you mean that the scenario can be solved by multiple validation groups?

**Comment by samdark** [comment]
Yes. Even in Yii 1 and Yii 2 it was a good thing to do separate form models instead of re-using ActiveRecord with scenarios everywhere (it was OK for simple cases though).

**Comment by kamarton** [comment]
I rarely used scenario, sounds good.
