### ISSUE TITLE
Groups / scenarios concept

### ISSUE THREAD

**Issue by arogachev** [yiisoft/validator#385]
- https://t.me/yii3ru/76804
- https://symfony.com/doc/current/validation/groups.html
- https://www.yiiframework.com/doc/guide/2.0/en/structure-models#scenarios

**Comment by samdark** [comment]
I prefer not to implement scenarios intentionally. While these are convenient at first, they lead an object to be re-used for multiple cases. Later these cases diverge and you end up with a huge mess.

**Comment by arogachev** [comment]
@samdark If it's possible to achieve with the current code base, maybe at least document it as an available option / alternative?

**Comment by BoShurik** [comment]
It would be nice to have such case in demo apps. E.g. require user password on creation and allow empty on editing. Now this use case not implemented (users created in fixtures and console commands)
