### ISSUE TITLE
Rename `InRange` rule and handler

### ISSUE THREAD

**Issue by arogachev** [yiisoft/validator#388]
Current possible options:

- `OneOf`.
- `IsIn`.

**Comment by samdark** [comment]
I love `OneOf`.

**Comment by arogachev** [comment]
The other option is simply `In`, quite short.  @vjik likes it. What do you think about that one? @samdark

**Comment by vjik** [comment]
For me both `OneOf` and `In` is OK. `IsIn` worse, non-consistent with other rule names.

**Comment by samdark** [comment]
`In` is fine.

**Comment by arogachev** [comment]
OK, let's stick with `In`.
