### ISSUE TITLE
Add `trimString` option to `Require` rule

### ISSUE THREAD

**Issue by vjik** [yiisoft/validator#390]

**Comment by arogachev** [comment]
I think it's redundant because we do not limit empty criteria to just `WhenEmpty` and there can be more combinations with parameters etc.

**Comment by arogachev** [comment]
It's `WhenEmpty(trimString: true)` vs `trimString: true`. Not much shorter. If well documented, using this should be no problem.

**Comment by vjik** [comment]
Agree.
