### ISSUE TITLE
Consider clientside validation

### ISSUE THREAD

**Issue by samdark** [yiisoft/validator#43]
Need to think about possible ways to implement clientside validation.

1. It could be done in pure JS or any JS framework.
2. This library should not have any JS.

Likely that could be introducing a way to convert rules to array that later could be JSON-ized and passed to client side.

**Comment by mamadza** [comment]
I think one of most interesting feature in yii2 is clientside validation , It's more interesting to have this in yii3 to any way , with more options

**Comment by xepozz** [comment]
If it will be implemented like a fully separeted package then ok.
It would be cool to have 3 packages of validators: 
1. yiisoft/validator
  Fully native-php validator
2. yiisoft/js-validator
  Fully native-js validator
3. yiisoft/js-validator-bridge
  Bridge between previous packages.

But I bet that JS world have own package for validators.
We can just implement bridge to it. It would be greatful solution for now.

**Comment by kamarton** [comment]
One of the main goals could be for the javascript validator to useable with multiple javascript frameworks. I'm thinking of solving it so that it can be solved with vue.js, jquery and future libs. 

It might be a solution to include a validation descriptor in the HTML tag, e.g. `<form data-rules="{descriptor}">` or `<input data-rule="{descriptor}">`.

It might be advisable to treat javascript pages completely separately, I also think about error messages. Javascript is hackable, so for final validation it is trusted by the PHP side, which can only be accepted by form-uploads after ajax or POST.

**Comment by samdark** [comment]
It is not the job of the validator package to generate HTML so instead it can return something like

```php
[
    'attribute1' => [
        'number',
        'max' => 10,
    ],
    'attribute2' => [
        'required'
    ],
]
```

**Comment by kamarton** [comment]
> It is not the job of the validator package to generate HTML so instead it can return something like

I did not intend to generate HTML tags. Basically I think it is necessary to decide where the descriptor is loaded from, since it can affect its processing and thus the code it generates.

**Comment by kamarton** [comment]
The client-side rule is optional, so I suggests defining an interface for `Rule` and `Validator` classes.

**Comment by samdark** [comment]
Would using `asOptions(): array` do?

**Comment by kamarton** [comment]
> Would using `asOptions(): array` do?

What happens if Rule does not support client-side validation? e.g. check domain by reverse DNS. In this case, return with an empty array?

**Comment by kamarton** [comment]
how about `asDescriptor()`? The return value could include type identification as well as options. e.g.
```php
[
  "attributeX" => [["__type"=>"string", "min" => 30], ["__type" => ...]],
],
```

**Comment by samdark** [comment]
> What happens if Rule does not support client-side validation? e.g. check domain by reverse DNS. In this case, return with an empty array?

Yes. Either that or just name of the rule and attribute.

**Comment by samdark** [comment]
So full validator return for:

```php
$validator = new Validator([    
    'amount' => [
        (new Number())->integer()->max(100),
        static function ($value): Result {
            $result = new Result();
            if ($value === 13) {
                $result->addError('Value should not be 13!');
            }
            return $result;
        }
    ],
    'name' => [
       (new HasLength)->max(20)
    ],
]);
```

Could be:

```
[
    'amount' => [
        ['number', 'integer' => true, 'max' => 100],
        ['not_13'],
    ],
    'name' => ['length', 'max' => 20],
]
```

So essentially each Rule has a name and an array of named options. Validator has arrays of these indexed by attributes.

Methods to add:

- Rule::getName(): string
- Rule::getOptions(): array
- Rules::asArray(): array
- Validator::asArray(): array

**Comment by demonking** [comment]
how could we handle not_13 ?
what happens if it's an compare to an string instead of a number?

**Comment by samdark** [comment]
> how could we handle not_13 ?

In this library we won't handle it. We'll give out information that the validation rule here is "not_13". It's up to clientside validation and form builder to decide on how to deal with it.

**Comment by samdark** [comment]
Additionally there should be a way to configure validation with array.

**Comment by samdark** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Prepare validators for clientside validation](https://trello.com/c/WQOoiorB/26-prepare-validators-for-clientside-validation)

**Comment by darkdef** [comment]
Needly by return messages from getOptions?
For example from class Number::$tooSmallMessage

**Comment by samdark** [comment]
Yes, I think so.
