### ISSUE TITLE
Add configurable default value to `DataSetInterface::getAttributeValue()`

### ISSUE THREAD

**Issue by arogachev** [yiisoft/validator#432]
https://github.com/yiisoft/validator/blob/d0765827ad0afa0304379ccbb32e7bb5d976b5d1/src/DataSetInterface.php#L12

**Comment by vjik** [comment]
Maybe rename `getAttributeValue()` to `getAttribute()` also?

**Comment by arogachev** [comment]
A workaround is to use `hasAttribute()` but it would be more clear and helpful.

**Comment by arogachev** [comment]
> Maybe rename `getAttributeValue()` to `getAttribute()` also?

For consistency with `hasAttribute()`, right?

**Comment by vjik** [comment]
> > Maybe rename `getAttributeValue()` to `getAttribute()` also?
> 
> For consistency with `hasAttribute()`, right?

For simplify only

**Comment by vjik** [comment]
> We can use `??`, right?

We don't can override default value. Suggestion:

```php
$dataSet->getAttributeValue('key', null); // return null if attribute "key" not exists
$dataSet->getAttributeValue('key', 0); // return 0 if attribute "key" not exists
```

**Comment by samdark** [comment]
`$dataSet->getAttributeValue('key') ?? 0`

**Comment by samdark** [comment]
I agree.
