### ISSUE TITLE
Unnesessary dependencies

### ISSUE THREAD

**Issue by viktorprogger** [yiisoft/validator#51]
- `intl` php extension usage is very occasional. And there are also a couple of exceptions which say "_intl extension must be installed and enabled_".
- Usage of `IP` rule is not a must too, but it requires `yiisoft/network-utilities`. But there must be a check with an exception thrown like with the `intl` extension done.

I think this package should only suggest to install `yiisoft/network-utilities` and `ext-intl` and not require them. This way rules should check if the needed dependecy presents and throw an exception if it is not.

**Comment by xepozz** [comment]
`intl` will be removed when `yiisoft/i18n-translator` was required.
Maybe `IPValidator` should be transferred to `yiisoft/network-utilities` packet?

**Comment by samdark** [comment]
> Maybe IPValidator should be transferred to yiisoft/network-utilities packet?

You propose reversing dependency? I think it's OK now.

**Comment by xepozz** [comment]
Yes, `yiisoft/network-utilities` will have `IPValidator`, that depends on `yiisoft/validator`

**Comment by samdark** [comment]
Removed intl dependency since it's checked in the validator. Decided not to remove `network-utilities`. Added i18n dependency.
