### ISSUE TITLE
Improve naming for empty criteria

### ISSUE THREAD

**Issue by arogachev** [yiisoft/validator#513]
Currently it's "criteria" for both singular and plural forms which is incorrect - https://en.wiktionary.org/wiki/criteria

The option for current name is to use "criterion" with a singular form. Or maybe use another name, like "condition"?

**Comment by vjik** [comment]
"Condition" is fine for me.

**Comment by arogachev** [comment]
OK, but let's wait for merging guide though.

**Comment by samdark** [comment]
I agree with "condition".
