### ISSUE TITLE
Class Structure for Number/Integer Validator

### ISSUE THREAD

**Issue by cebe** [yiisoft/validator#531]
### What steps will reproduce the problem?

Current implementation of Number validator has two properties: `integerPattern` and `numberPattern`, of which only one is relevant if you make the `integerOnly` switch. From a design perspective it might be better to design the Integer validator to extend from the Number validator and define the pattern differently.

In the current implementation I can provide properties that have no effect, or I can break my code easily:

```php
$rule = new Number(numberPattern: '...');
```

if I now add the integerOnly to true, I might not be aware that the pattern has no effect anymore.

```diff
-$rule = new Number(numberPattern: '...');
+$rule = new Number(numberPattern: '...', integerOnly: true);
```

This would be better imo:

```php
$rule = new Number(pattern: '...');
```

making the change:

```diff
-$rule = new Number(numberPattern: '...');
+$rule = new Integer(numberPattern: '...');
```

pattern still applies.

What do you think?

**Comment by vjik** [comment]
I like this idea. And parameter ”numberPattern” rename to pure "pattern".

**Comment by arogachev** [comment]
Sounds alright. I had the idea of adding shortcut for integer too. But then I thought maybe it's not worth it like with `Compare` shortcuts or there will be too many of them.

With the current approach we can at least add the exceptions with hints for wrong combinations of arguments.

**Comment by samdark** [comment]
Yes, it makes sense. Let's do it.
