### ISSUE TITLE
Getting access to attributes out of nested validation context

### ISSUE THREAD

**Issue by bouledepate** [yiisoft/validator#558]
Hello. I have a problem when I try to write conditional validation using ValidationContext object and trying to get attribute value, which not included into Nested collection. For example, I have this:
```(php)
$rules = [
    'method' => [new Required()],
    'attributes' => new Nested([
        'abc' => [new Required(when: static function (mixed $value, ValidationContext $context): bool {
            $method = $context->getDataSet()->getAttributeValue('method');
            return $method === Method::POST->value;
        }),
        ...
    ])
];
```
When I try to get value via $context->getDataSet()->getAttributeValue('method'), I got null. But If this condition will not be in Nested collection, I receive needed value.

Documentation says: "$context->getDataSet()->getAttributeValue() method allows you to get any other attribute's value within the ValidationContext". Does it mean I must have access those attributes from Nested ValidationContext or not? Or what kind of attributes must be included into validation context?

**Comment by arogachev** [comment]
Thanks for reporting! Fixed in #559.
