### ISSUE TITLE
Cannot change defaultSkipOnEmpty

### ISSUE THREAD

**Issue by tomaszkane** [yiisoft/validator#567]
### What steps will reproduce the problem?
Add DI definition:
```php
Validator::class => [
    'class' => Validator::class,
    '__construct()' => [
        // some other config here...
        'defaultSkipOnEmpty' => false,
    ],
],
```
### What is the expected result?

I want to `Container::get(Validator::class)` and optionally change `defaultSkipOnEmpty` to validate different context.

### What do you get instead?

`defaultSkipOnEmpty` cannot be changed, so I must add two definitions to DI, like:
```php
Validator::class => [
    'class' => Validator::class,
    '__construct()' => [
        // some other config here...
        'defaultSkipOnEmpty' => false,
    ],
],
'LazyValidator' => [
    'class' => Validator::class,
    '__construct()' => [
        // some other config here...
        'defaultSkipOnEmpty' => true,
    ],
],

```
with is ugly.

### Additional info

| Q                | A
| ---------------- | ---
| PHP version      | 8.0

**Comment by samdark** [comment]
Do you need two validator instances in the same request?

**Comment by tomaszkane** [comment]
Hm, no its two requests.

First is api /validate to validate given data (all or part) - "validate what user send".

Second is /create - "validate all data needs to save record" so empty or missing values is not acceptable.

**Comment by samdark** [comment]
I see. So, an immutable method would do.
