### ISSUE TITLE
Missing StringValue rule

### ISSUE THREAD

**Issue by arrilot** [yiisoft/validator#594]
This very basic rule is pretty much required when we use validator in a context like https://github.com/yiisoft/request-model
Imagine we want to decode JSON body and check that particular JSON fields are strings

There are `BoolValue`, `TrueValue` and `IntegerValue` rules, but `StringValue` seems to be missing.
There is also a workaround with an empty `Length` rule but using it for validation variable type is kinda strange.

**Comment by arogachev** [comment]
Should it support `\Stringable`?

**Comment by arrilot** [comment]
I don't have a strong opinion on that matter but I guess no:
1. e.g. Length rule [uses is_string](https://github.com/yiisoft/validator/blob/master/src/Rule/LengthHandler.php#L31). Why would StringVal rule adhere Stringable aswell?
2. Symfony validator uses simple is_string for Type('string') aswell https://github.com/symfony/validator/blob/6.2/Constraints/TypeValidator.php#L33

**Comment by vjik** [comment]
> Should it allow `\Stringable` as well?

Maybe add option `allowStringable` with `false` as default?

**Comment by arogachev** [comment]
@vjik And in the `Length` too?

**Comment by vjik** [comment]
> @vjik And in the `Length` too?

I would add to `Length` when there is a need for it.

**Comment by arogachev** [comment]
As for `StringValue::$allowStringable` - suggest to do it in a separate PR, maybe discuss more.
