### ISSUE TITLE
Ability add base result before validation

### ISSUE THREAD

**Issue by vjik** [yiisoft/validator#598]
My suggestion: add ability add base result to `Context` and use [here](https://github.com/yiisoft/validator/blob/b0044e016768cdfa40d451612da054d6d3bf2162/src/Validator.php#L122).

Use case: input model with prevalidation raw data.

**Comment by samdark** [comment]
What is prevalidation data?

**Comment by vjik** [comment]
Raw values and populated values can be different. My service validate raw data into populate process and then run classic validation. 

For example:

```php
final class SimpleModel implements ValidatedModelInterface
{
    use ValidatedModelTrait;

    public function __construct(
        #[PreValidate(new Required())]
        #[Length(min: 3, skipOnError: true)]
        public string $a = '.',
        public string $b = '.',
        public string $c = '.',
    ) {
    }
}

$service->create(SimpleModel::class, data: []);
```

In raw data `a` not exists and `Required` add error. Then length should not add error because option `skipOnError` is true.

**Comment by BoShurik** [comment]
Why don't you use separate models: for user input (with raw data) and model with populated data (converted from user input)?

**Comment by vjik** [comment]
> Why don't you use separate models: for user input (with raw data) and model with populated data (converted from user input)?

Not convient. One input model is simple.

**Comment by samdark** [comment]
It is a lazy approach that is convenient at first but:

1. It complicates validator.
2. The use-case is not common enough.
3. With application growth these two layer inputs are likely to diverge more and such approach will create more problems than it is trying to solve.

Overall, I don't think it is a good idea.

**Comment by vjik** [comment]
Decided don't make it, because use-case is changed: if pre validation is fail then not run validation.
