### ISSUE TITLE
Date and datetime string validator

### ISSUE THREAD

**Issue by samdark** [yiisoft/validator#602]
`DateRule` validates a string value that represents a date. `DateTimeRule` validates a string value that represents date and time.

# Options

`format`, see [DateTime::createFromFormat()](https://secure.php.net/manual/en/datetime.createfromformat.php)

For `Date` default could be 'Y-m-d', for `DateTime` it could be `Y-m-d H:i:s`.

# Implementation

Use `\DateTime::createFromFormat()` then `\DateTime::getLastErrors()` or regex + validating if date and time are valid.

**Comment by samdark** [comment]
- https://github.com/symfony/symfony/blob/6.2/src/Symfony/Component/Validator/Constraints/DateTimeValidator.php
- https://github.com/symfony/symfony/blob/6.2/src/Symfony/Component/Validator/Constraints/DateValidator.php

**Comment by Gerych1984** [comment]
I wrote a similar one for my needs (need to fix nymspaces). It may be useful with a little tweaking
[DateTime.zip](https://github.com/yiisoft/validator/files/13203625/DateTime.zip)
