### ISSUE TITLE
Disscusion: Using native php filter_var functions instead of regex

### ISSUE THREAD

**Issue by Gerych1984** [yiisoft/validator#629]
Good day. I have a question that has been lingering since version 2 - why url/email/numeric validators use own regulars instead of native functions? It seems that their built in functionality is enough to cover the validator's needs. Thanks

**Comment by samdark** [comment]
Could be. Likely that's because native functions are too strict but I don't remember the reason for regex.

**Comment by vjik** [comment]
Because native functions work incorrectly in same edge cases.

For example:

```php
$value = '"attacker\"\ -oQ/tmp/\ -X/var/www/cache/phpcode.php"@email.com';
filter_var($value, FILTER_VALIDATE_EMAIL) !== false; // Valid, but really it's invalid.

$value = '020';
filter_var($value, FILTER_VALIDATE_INT) !== false; // Invalid, but really it's correct integer number.

$value = 'http://example.com:?test';
filter_var($value, FILTER_VALIDATE_URL) !== false; // Valid, but really it's invalid.
```
