### ISSUE TITLE
Move out `getName()` from `RuleInterface`

### ISSUE THREAD

**Issue by arogachev** [yiisoft/validator#634]
Case - REST API without usage on the frontend, serialization of rules are not required.

**Comment by vjik** [comment]
What use as name for rules without name?

**Comment by arogachev** [comment]
If there is an attempt to serialize the rule without name, an exception can be thrown for example.

**Comment by BoShurik** [comment]
We may use FQCN as a name

**Comment by vjik** [comment]
After discussion, we came to the following decision.

1. Move `getName()` from `RuleInterface` to `RuleWithOptionsInterface`.
2. Built-in rules must returns own FQCN as rule name.
3. `RulesDumper` for rules that not implemented `RuleWithOptionsInterface`, use rule FQCN as name and empty array as options.
4. Rename `RuleWithOptionsInterface` to more correct name.

**Comment by arogachev** [comment]
@BoShurik Thanks for your suggestion.
