### ISSUE TITLE
Add methods `getFirstErrorMessagesIndexedByAttribute()` and `getFirstErrorMessagesIndexedByPath()` to `Result` class

### ISSUE THREAD

**Issue by vjik** [yiisoft/validator#649]

**Comment by arogachev** [comment]
Should a single error be string or string within array (for structure to be consistent with similar methods)?

**Comment by vjik** [comment]
> Should a single error be string or string within array (for structure to be consistent with similar methods)?

String only.

Example for `getFirstErrorMessagesIndexedByAttribute()`:

```php
[
  'name' => 'error...',
  'age' => 'error...',
]
```
