### ISSUE TITLE
Can rule Integer allow only 'int'?

### ISSUE THREAD

**Issue by gotyefrid** [yiisoft/validator#655]
Now "Integer" validator allows three types of variables - they are integer, float and string.
Is it possible to make the property accept ONLY integer type?

For example

```php
$rule = new Integer(strict: true);
```
or
```php
$rule = new Integer(allowTypes: ['int', 'float']);
```

**Comment by vjik** [comment]
Currently it is not supported.

I think for this case better make new rule that check value type, and use it combined with `Integer` rule. For example:

```php
#[Type(allows: [Type::Integer, Type::Float])]
#[Integer(min: 95)]
```
