### ISSUE TITLE
Replace `mixed $skipOnEmpty` in rules constructors to `bool|callable|null $skipOnEmpty`

### ISSUE THREAD

**Issue by vjik** [yiisoft/validator#660]
Example rule where already implemented it: `Equal`.

**Comment by arogachev** [comment]
Do you mean to change it only for arguments (not properties) like this?

```php
mixed $skipOnEmpty
```

**Comment by vjik** [comment]
> Do you mean to change it only for arguments (not properties) like this?
> 
> ```
> mixed $skipOnEmpty
> ```
> 
> Because in properties `callable` type is not allowed.

yes

**Comment by vjik** [comment]
Done by #698
