### ISSUE TITLE
How to validate an optional field?

### ISSUE THREAD

**Issue by mister-42** [yiisoft/validator#74]
### What steps will reproduce the problem?
Validate field `recipient`, but it's optional (No `new Required()`).
```php
public function rules(): array
{
    return [
        'recipient' => [(new Email())->checkDNS(true)->enableIDN(true)],
    ];
}
```
Filling the form and it submits. Filling the form except `recipient` fails with error.

### What is the expected result?
Form submits without error.

### What do you get instead?
`This value is not a valid email address.`

### Additional info

| Q                | A
| ---------------- | ---
| Version          | current dev
| PHP version      | 7.4.8
| Operating system | Debian 10

**Comment by Thoulah** [comment]
My current workaround:

```php
public function rules(): array
{
    return [
        'recipient' => [empty($this->getAttributeValue('recipient')) ? new Callback(function () {
            $result = new Result();
            return $result;
        }) : (new Email())->checkDNS(true)->enableIDN(true)],
    ];
}
```

There must be an easier way!

**Comment by samdark** [comment]
There is an easier way:

```php
public function rules(): array
{
    return [
        'recipient' => new Email())->checkDNS(true)->enableIDN(true)->skipOnEmpty(true),
    ];
}
```

**Comment by Thoulah** [comment]
Doh!
Thank you very much.

**Comment by samdark** [comment]
It's actually in readme. Section is called "Skipping empty values".
