### ISSUE TITLE
PHP 8 attributes support

### ISSUE THREAD

**Issue by armpogart** [yiisoft/validator#77]
One of the best use cases for the new feature of annotations in PHP 8 is using them for validators. There is also an option to support validators on on PHP 7.4 with the help of [Doctrine Annotations](https://github.com/doctrine/annotations), but it would need more work and I'm not sure whether it is worth it.

**Comment by samdark** [comment]
Where would you put these annotations? Maybe you've meant https://github.com/yiisoft/form/blob/master/src/FormModel.php?

**Comment by armpogart** [comment]
Yes, it will primarily used in `FormModel`, but we have also `DataSetInterface` here that can leverage using annotated validators.

**Comment by samdark** [comment]
So that could be something like named constructor:

```php
$validator = Validator::fromAnnotatedDataSet($data);
$results = $validator->validate($data);
```

Right?

**Comment by armpogart** [comment]
Yes, we will need something like that to receive the DataSetInterface` implementation and parse all attributes using reflection and do the validation.
So we will have validator attributes in this package that will be used both here and in `yiisoft/forms`.

**Comment by samdark** [comment]
OK. Let's wait for next beta of PHP 8. Attributes will likely be adjusted there.

**Comment by BoShurik** [comment]
It's not applicable if rules needs dependencies in current implementation

**Comment by samdark** [comment]
@BoShurik what do you mean

**Comment by BoShurik** [comment]
@samdark If I have custom rule:
```php
final class Phone extends Rule
{
    public function __construct(\libphonenumber\PhoneNumberUtil $phoneUtil)
    {
        // ...
    }
}
```
How to inject this dependency?

**Comment by samdark** [comment]
@BoShurik by putting your instance of GroupRule or Rule into container?

**Comment by BoShurik** [comment]
@samdark do you suggest to use rule class as an attribute or create separate attribute for rule (e.g. `Phone` and `PhoneAttribute`)? I mean first approach is impossible since rule may have a dependency.

**Comment by samdark** [comment]
I don't get it. Why would I need to put a rule class into an attribute?

```php
class MyRule
{
    private WeirdChecker $weirdChecker;

    public function __construct(WeirdChecker $weirdChecker)
    {
        $this->weirdChecker = $weirdChecker;
    }
}

class MyForm extends FormModel
{
    private MyRule $myRule;

    public function __construct(MyRule $myRule)
    {
        $this->myRule = $myRule;       
    }
}

public function actionIndex(MyForm $form)
{
   // ...
}
```

**Comment by BoShurik** [comment]
How you suggest to support php attributes? For each rule create an attribute class which must be converted to its rule?

**Comment by samdark** [comment]
Ah! Finally got it :) You mean something like the following, right?


```php
#[Attribute::TARGET_PROPERTY]
class Validate
{
    public function __construct(string $rule, array $parameters = [])
    {
        // ..
    }

    public function getData(): array
    {
       // ...
    }
}

class AttributeFormModel
{
    private ValidatorFactoryInterface $validatorFactory;

    public function __construct(AttributeValidatorFactory $validatorFactory)
    {
        $this->validatorFactory = $validatorFactory;
    }

    public function rules(): array
    {
        $class = new ReflectionClass($this);
        $rules = [];

        foreach ($class->getProperties() as $property) {
            if ($property->isStatic()) {
                continue;
            }

            $attributes = $property->getAttributes(Validate::class);
            foreach ($attributes as $validatorAttribute) {
                $rules[$property->getName()][] = $validatorAttribute->getData();
            }
        }

        return $rules;
    }
}
```

**Comment by samdark** [comment]
Here's a good reference btw., till the manual is ready: https://stitcher.io/blog/attributes-in-php-8

**Comment by arogachev** [comment]
Let's decide, is it needed for 1.0.0? I think it's indeed a cool thing to have, but can wait for the next release (after 1.0.0). Maybe vote under this post using :+1: / :-1:? @yiisoft/yii3 

By the way, PHP 7.4 is still supported, so this can be optional.

**Comment by arogachev** [comment]
Need to dig deeper into this though. :thinking:

**Comment by samdark** [comment]
If depends on how it will affect public API. If it will change it then it worth considering doing it now. If not, doing it later is fine.
